# .gitleaks.toml

[extend]
useDefault = true

[allowlist]
paths = [
 ’’’\.example\.js$’’’,
 ’’’package-lock\.json’’’,
 ’’’test/.*’’’
]

[[rules]]
id = ”custom-eni-token”
description = ”Token interne ENI”
regex = ’’’ENI_TOKEN_[a-zA-Z0-9]{32}’’’
entropy = 3.5
